version: '3.9'

services:

  # front-end React
  web:
    container_name: web
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=dev-js
      - NODE_PORT=3001
    command: [yarn, start]
    volumes:
      - .:/web

  # back-end SQLite
  api:
    container_name: api
    build: ./backend
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=dev-js
      - NODE_PORT=3001
    entrypoint: [yarn, dev]
    volumes:
      - .:/app
