# Generated by Django 4.1 on 2022-10-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=1)),
                ("date", models.CharField(max_length=8)),
                ("value", models.CharField(max_length=10)),
                ("cpf", models.CharField(max_length=11)),
                ("card", models.CharField(max_length=12)),
                ("time", models.CharField(max_length=6)),
                ("owner", models.CharField(max_length=14)),
                ("outlet", models.CharField(max_length=19)),
            ],
        ),
    ]
