# Generated by Django 4.1 on 2022-10-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="entry",
            name="time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="entry",
            name="type",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="entry",
            name="value",
            field=models.IntegerField(),
        ),
    ]
